

exports.CLIENT_REQUEST_LOGIN   = 201;
exports.SERVER_RESPONSE_LOGIN  = 202;

exports.SERVER_REQUEST_STARTGROUPACTIVITY=	203;
exports.CLIENT_RESPONSE_STARTGROUPACTIVITY=	204;

exports.SERVER_REQUEST_GROUPDECISION=	205;	
exports.CLIENT_RESPONSE_GROUPDECISION=	206;
exports.CLIENT_REQUEST_GROUPATTEND=	207;
exports.SERVER_RESPONSE_GROUPATTEND=	208;

exports.SERVER_REQUEST_GROUPIN=	209;	
exports.CLIENT_RESPONSE_GROUPIN=	210;
exports.SERVER_REQUEST_GROUPINGCOMPLETE=	211;
exports.CLIENT_RESPONSE_GROUPINGCOMPLETE=	212;

exports.SERVER_REQUEST_STARTWORKSHEETACTIVITY =	213;
exports.CLIENT_RESPONSE_STARTWORKSHEETACTIVITY =	214;
exports.CLIENT_REQUEST_WORKSHEETPROGRESS=	215;
exports.SERVER_RESPONSE_WORKSHEETPROGRESS=	216;
exports.CLIENT_REQUEST_WORKSHEETRESULT = 217;
exports.SERVER_RESPONSE_WORKSHEETRESULT=	218;
exports.SERVER_REQUEST_STARTREPRESENTATIONACTIVITY=	219;
exports.CLIENT_RESPONSE_STARTREPRESENTATIONACTIVITY=	220;
exports.CLIENT_REQUEST_REPRESENTATIONPROGRESS=	221;
exports.SERVER_RESPONSE_REPRESENTATIONPROGRESS=	222;
exports.CLIENT_REQUEST_REPRESENTATIONSYNC=	223;
exports.SERVER_RESPONSE_REPRESENTATIONSYNC=	224;
exports.SERVER_REQUEST_REPRESENTATIONSYNC=	225;
exports.CLIENT_RESPONSE_REPRESENTATIONSYNC=	226;
exports.CLIENT_REQUEST_REPRESENTATIONSEND=	227;
exports.SERVER_RESPONSE_REPRESENTATIONSEND=	228;
exports.SERVER_REQUEST_STARTATTENDACTIVITY=	229;
exports.CLIENT_RESPONSE_STARTATTENDACTIVITY=		230;
exports.CLIENT_REQUEST_ATTEND=	231;
exports.SERVER_RESPONSE_ATTEND=	232;
exports.CLIENT_REQUEST_CONNECTION	=	233;
exports.SERVER_RESPONSE_CONNECTION=	234;
